general:
  debug_level: DEBUG

  # paths
  input_filelist_path: "../input/filelist.txt"
  input_sumweights_path: "../input/sum_of_weights.txt"
  output_path_histograms: "../output/"
  output_path_ntuples: "../output/"

  # weights
  default_sumweights: "NOSYS"
  default_event_weights: "weight_mc_NOSYS * weight_pileup_NOSYS * weight_jvt_effSF_NOSYS * weight_btagSF_DL1dv01_Continuous_NOSYS * globalTriggerEffSF_NOSYS * weight_leptonSF_tight_NOSYS"

  default_reco_tree_name: "reco"

  # path to the file with cross-sections
  xsection_files: ["data/XSection-MC21-13p6TeV.data"]

  # name of the custom class
  custom_frame_name: "TutorialClass"

  # automatic systematics?
  automatic_systematics: True
  nominal_only: False

  # which objects to create lorentz vectors for
  create_tlorentz_vectors_for: ["jet"]

  number_of_cpus: 4


# define regions
regions:
  - name: "Electron"
    selection: "pass_ejets_NOSYS"
    variables:
      - name: "jet1_pt_GEV"
        title : "Leading jet p_{T}; Leading jet p_{T} [GeV];Events"
        definition: "jet1_pt_GEV_NOSYS"
        type: "double"
        binning:
          min: 0
          max: 300
          number_of_bins: 10
      - name: "reco_met"
        title : "MET;E_{T}^{miss} [MeV];Events"
        definition: "met_met_NOSYS"
        type: "float"
        binning:
          bin_edges: [0,20000,60000,80000,140000,250000]

  - name: "Muon"
    selection: "pass_mujets_NOSYS"
    variables:
      - name: "jet1_pt_GEV"
        title : "Leading jet p_{T}; Leading jet p_{T} [GeV];Events"
        definition: "jet1_pt_GEV_NOSYS"
        type: "double"
        binning:
          min: 0
          max: 300
          number_of_bins: 10
      - name: "reco_met"
        title : "MET;E_{T}^{miss} [MeV];Events"
        definition: "met_met_NOSYS"
        type: "float"
        binning:
          bin_edges: [0,20000,60000,80000,140000,250000]


# define samples
samples:
  - name: "ttbar_FS"
    dsids: [601229]
    campaigns: ["mc23a"]
    simulation_type: "fullsim"

ntuples:
  selection: "pass_ejets_NOSYS"
  copy_trees: ["particleLevel"]

